POST http://localhost:5000/employees

{"eName":"Michael Castro","eID": 12}
###

POST http://localhost:5000/employees

{"eName":"Meghan Castro","eID": 13}
###

POST http://localhost:5000/employees

{"eName":"Michelle Castro","eID": 12}
###

GET http://localhost:5000/employees

###

GET http://localhost:5000/employees/12

###

GET http://localhost:5000/employees/15

###

DELETE http://localhost:5000/employees/13

###

DELETE http://localhost:5000/employees/15

###

PUT http://localhost:5000/employees/12

{"eName":"Michelle Castro"}

###

POST http://localhost:5000/employees/12/expenses

{"expid":1,"expammount":1250.50}

###

POST http://localhost:5000/employees/12/expenses

{"expid":2,"expammount":12.00}

###

POST http://localhost:5000/employees/12/expenses

{"expid":3,"expammount":120.00}

###

POST http://localhost:5000/employees/12/expenses

{"expid":4,"expammount":-200.00}

###

GET  http://localhost:5000/employees/12/expenses

###

GET  http://localhost:5000/employees/12/expenses/1

###

GET  http://localhost:5000/employees/12/expenses/5

###

GET http://localhost:5000/employees/12/expenses?approval=Pending

###

GET http://localhost:5000/employees/12/expenses?status=Approved

###

GET http://localhost:5000/employees/12/expenses?approval=Denied

###

PUT http://localhost:5000/employees/12/expenses/1

{"approval":"Pending"}

###

PATCH http://localhost:5000/employees/12/expenses/1/Denied

###

PATCH http://localhost:5000/employees/12/expenses/1/Approved


###

DELETE http://localhost:5000/employees/12/expenses/2/Pending


###

DELETE http://localhost:5000/employees/12/expenses/1/Denied
