POST http://localhost:5000/employee

{"eName":"Michael Castro","eID": 12}
###

POST http://localhost:5000/employee

{"eName":"Meghan Castro","eID": 13}
###

POST http://localhost:5000/employee

{"eName":"Michelle Castro","eID": 12}
###

GET http://localhost:5000/employee

###

GET http://localhost:5000/employee/12

###

GET http://localhost:5000/employee/15

###

DELETE http://localhost:5000/employee/12

###

PUT http://localhost:5000/employee/12

{"eName":"Michelle Castro"}

###

POST http://localhost:5000/employee/12/expense

{"expid":1,"expammount":1250.50, "approval":"Pending"}

###

POST http://localhost:5000/employee/12/expense

{"expid":2,"expammount":12.00, "approval":"Pending"}

###

POST http://localhost:5000/employee/12/expense

{"expid":3,"expammount":120.00, "approval":"Approved"}

###

GET  http://localhost:5000/employee/12/expense

###

GET  http://localhost:5000/employee/12/expense/1

###

GET  http://localhost:5000/employee/12/expense/5

###

GET http://localhost:5000/employee/12/expense?approval=Pending

###

PUT http://localhost:5000/employee/12/expense/2

{"approval":"Pending"}

###

PATCH http://localhost:5000/employee/12/expense/1/Pending

{"approval":"Denied"}

###

PATCH http://localhost:5000/employee/12/expense/1/Denied

{"approval":"Approved"}

###

DELETE http://localhost:5000/employee/12/expense/3

###

DELETE http://localhost:5000/employee/12/expense/1