POST http://localhost:5000/employees

{"eName":"Michael","eID": 12}
###

POST http://localhost:5000/employees

{"eName":"Meghan","eID": 13}
###

POST http://localhost:5000/employees

{"eName":"Michelle","eID": 12}
###

GET http://localhost:5000/employees

###

GET http://localhost:5000/employees/12

###

GET http://localhost:5000/employees/15

###

DELETE http://localhost:5000/employees/13

###

DELETE http://localhost:5000/employees/15

###

PUT http://localhost:5000/employees/12

{"eName":"Michelle"}

###

POST http://localhost:5000/expenses

{"eid":12, "expid":1221,"expammount":1250.50, "approval":"Pending"}

###

POST http://localhost:5000/employees/12/expenses

{"expid":121,"expammount":1250.50, "approval":"Pending"}

###

POST http://localhost:5000/employees/12/expenses

{"expid":122,"expammount":12.00,"approval":"Pending"}

###

POST http://localhost:5000/employees/12/expenses

{"expid":123,"expammount":120.00, "approval":"Pending"}

###

POST http://localhost:5000/employees/12/expenses

{"expid":124,"expammount":-200.00, "approval":"Pending"}

###

GET  http://localhost:5000/expenses

###

GET  http://localhost:5000/employees/12/expenses/1221

###

GET  http://localhost:5000/employees/12/expenses/125

###

GET http://localhost:5000/expenses?status=Pending

###

GET http://localhost:5000/expenses?status=Approved

###

GET http://localhost:5000/expenses?status=Denied

###

PATCH http://localhost:5000/expenses/121/Denied

###

PATCH http://localhost:5000/expenses/121/Approved


###

DELETE http://localhost:5000/expenses/122/Pending


###

DELETE http://localhost:5000/expenses/121/Denied
